WebApp/Controllers/MaillistController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Repositories;

namespace WebApp.Controllers
{
	public class MaillistController : BaseController
	{
		public async Task<IActionResult> Index()
        {
            await LoadCommonData();

            return View();
		}
	}
}

WebApp/Views/Maillist/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_LayoutWebUITheme.cshtml";
}

<ul class="breadcrumb">
	<li>
		<a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i></a>
	</li>
	<li><a href="@Url.Action("Index","Account")">Hesabım</a></li>
	<li>
        <a href="@Url.Action("Index","Maillist")">Bülten Aboneliği</a>
	</li>
</ul>

<h1 class="title page-title"><span>Bülten Aboneliği</span></h1>

<div id="account-newsletter" class="container">
    <div class="row">
        <div id="content" class="col-sm-9">
            <form action="https://www.tilsimbaby.com/hesap/maillist"
                  method="post"
                  enctype="multipart/form-data"
                  class="form-horizontal">
                <fieldset>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Abonelik:</label>
                        <div class="col-sm-10">
                            <label class="radio-inline">
                                <input type="radio" name="newsletter" value="1" />
                                Evet
                            </label>
                            <label class="radio-inline">
                                <input type="radio"
                                       name="newsletter"
                                       value="0"
                                       checked="checked" />
                                Hayır
                            </label>
                        </div>
                    </div>
                </fieldset>
                <div class="buttons clearfix">
                    <div class="pull-left">
                        <a href="@Url.Action("Index","Account")"
                           class="btn btn-default">Geri</a>
                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-primary">
                            <span>Devam</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        @Html.Partial("_AccountSidebar")
    </div>
</div>